name: Test Maven - clean install

# Bude se spouštět ve všech třech situacích:
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK - Maven
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build - Maven
        run: mvn clean install
